---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure PHP packages are installed (RedHat).
  yum: >
    name={{ item }}
    state=installed
    enablerepo={{ php_enablerepo }}
  with_items: php_packages
  notify: restart webserver
  when: ansible_os_family == 'RedHat'

- name: Ensure PHP packages are installed (Debian).
  apt: >
    name={{ item }}
    state=installed
  with_items: php_packages
  notify: restart webserver
  when: ansible_os_family == 'Debian'

- name: Install PEAR libraries.
  command: pear install {{ item }}
  register: pear_result
  changed_when: "'already installed' not in pear_result.stdout"
  failed_when: "pear_result.stderr"
  with_items: php_pear_libraries

- name: Place PHP configuration files in place.
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root group=root mode=644
  with_items:
  - { src: php.ini.j2, dest: "{{ php_conf_path }}/php.ini" }
  - { src: apc.ini.j2, dest: "{{ php_extension_conf_path }}/{{ php_apc_conf_filename }}" }
  notify: restart webserver

- name: Ensure php-fpm is started and enabled at boot (if configured).
  service: name=php-fpm state=started enabled=yes
  when: php_enable_php_fpm
