---

- name: epel-release install
  yum: name=http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

- name: remi-release install
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

- name: wandisco-svn install
  copy: src=./yum.repos.d/wandisco-svn.repo                                                                                                                               
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644
