- hosts: servers
  sudo: yes
  user: vagrant
  vars_files:
    - ../private_vars/common.yml # リポジトリにコミットしない共通変数定義
  roles:
    - ../common-roles/repos
    - ../common-roles/base
    - ../common-roles/php
    - ../common-roles/apache
