- hosts: servers
  sudo: yes
  user: vagrant

  tasks:
    - name: install the latest version of Git
      yum: pkg=git state=latest
    - name: install the latest version of Vim 
      yum: pkg=vim state=latest
  roles:
    - ../common-roles/repos
    - ../common-roles/base
    - ../common-roles/php
#    - ../common-roles/mysql-server
